### ISSUE TITLE
Need help to run it

### ISSUE THREAD

**Issue by sajian** [Dissem/Abit#1]
Hello, I am trying to run this app, but there is an error that I don't know how to solve it.
In Singleton.java, I cannot resolve method 'security'.
Thank you very much.

**Comment by Dissem** [comment]
That one got renamed to cryptography (as about everything that once was called security) - where did you find this faulty description?

**Comment by sajian** [comment]
At here: https://github.com/Dissem/Abit/blob/master/app/src/main/java/ch/dissem/apps/abit/service/Singleton.java

I am so grateful for your prompt reply.

**Comment by Dissem** [comment]
You should use the development branch, at least for now - it fixes many issues. On the other hand, I really should merge it into master once in a while.

**Comment by AndyKD** [comment]
Hello, @Dissem 

   bitmessageContext = new BitmessageContext.Builder()
                            .nodeRegistry(new MemoryNodeRegistry())
                            .inventory(new AndroidInventory(sqlHelper))
                            .addressRepo(new AndroidAddressRepository(sqlHelper))
                            .messageRepo(new AndroidMessageRepository(sqlHelper, ctx))
                            .networkHandler(new DefaultNetworkHandler())
                            .listener(getMessageListener(ctx))
                            .cryptography(xxxx)
                            .build();

What should I passed the the place of xxx in '.cryptography(xxxx)' , I am not able to run this project, Please help me out.

Thanks In Advance.

**Comment by Dissem** [comment]
On Android devices you need SpongyCryprography, on the Oracle JVM I fear it doesn't work, so you'll need BouncyCryptography. I thought I got Spongy running on the desktop JVM but I think now it's just the OpenJDK behaving differently than the Oracle one.

**Comment by AndyKD** [comment]
@Dissem  Thanks for quick prompt, Can you please explore more, Can I use your development checkout for just running the demo?

Can you please send me request on skype: deepak.kumar3038

if you dnt mind :-)
